/// Provides details about the merchant associated with a given access token.  The access token used to connect your application to a Square seller is associated with a single merchant. That means that `ListMerchants` returns a list with a single `Merchant` object. You can specify your personal access token to get your own merchant information or specify an OAuth token to get the information for the merchant that granted your application access.  If you know the merchant ID, you can also use the [RetrieveMerchant]($e/Merchants/RetrieveMerchant) endpoint to retrieve the merchant information.
public struct ListMerchants: SquareAPIEndpoint {
	public static var method: HTTPMethod { return .GET }
	public typealias inputType = Empty
	public typealias outputType = ListMerchantsResponse
	public typealias paramType = Params
	public struct Params {
		let cursor: Int?
		/// Provides details about the merchant associated with a given access token.  The access token used to connect your application to a Square seller is associated with a single merchant. That means that `ListMerchants` returns a list with a single `Merchant` object. You can specify your personal access token to get your own merchant information or specify an OAuth token to get the information for the merchant that granted your application access.  If you know the merchant ID, you can also use the [RetrieveMerchant]($e/Merchants/RetrieveMerchant) endpoint to retrieve the merchant information.
		/// - Parameters:
		///   - cursor: The cursor generated by the previous response.
		public init(cursor: Int? = nil) {
			self.cursor = cursor
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		let url = "/v2/merchants"
		var queries = [String]()
		if let v = inputs.cursor { queries.append("cursor=\(v)") }
		if queries.count > 0 {
			let query = queries.joined(separator: "&")
			let encoded = query.addingPercentEncoding(withAllowedCharacters: .urlQueryAllowed)
			return url + "?" + (encoded ?? query)
		}
		return url
	}
}

/// Retrieves the `Merchant` object for the given `merchant_id`.
public struct RetrieveMerchant: SquareAPIEndpoint {
	public static var method: HTTPMethod { return .GET }
	public typealias inputType = Empty
	public typealias outputType = RetrieveMerchantResponse
	public typealias paramType = Params
	public struct Params {
		let merchant_id: String
		/// Retrieves the `Merchant` object for the given `merchant_id`.
		/// - Parameters:
		///   - merchant_id: The ID of the merchant to retrieve. If the string "me" is supplied as the ID, then retrieve the merchant that is currently accessible to this call.
		public init(merchant_id: String) {
			self.merchant_id = merchant_id
		}
	}
	public static func endpoint(for inputs: Params) throws -> String {
		let url = "/v2/merchants/\(inputs.merchant_id)"
		return url
	}
}

